### ISSUE TITLE
Sorting issues with Number fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#876]
See full discussion here: https://gravityview.slack.com/archives/G0RA23YHE/p1491951663897387

Issue: Wrong sort order: 1. 10. 2. 21, 22, 3.1

Looks like an issue with `is_numeric` on latest versions.

Related: https://secure.helpscout.net/conversation/347699749/0/ and https://secure.helpscout.net/conversation/346645365/8831/?folderId=408735

Tested on GV 1.21.3 (also affecting sort on DataTables)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995654411107787)

**Comment by soulseekah** [comment]
Fixed in c955155822bb3181a32eea2b2725d97fd5af39ea

**Comment by soulseekah** [comment]
This was merged in https://github.com/gravityview/GravityView/pull/874

Can close I assume?

**Comment by zackkatz** [comment]
Sure!

**Comment by altoin** [comment]
This issue is back in the latest Version of GravityView
https://secure.helpscout.net/conversation/734876757/18270?folderId=408730

**Comment by soulseekah** [comment]
Tests are still good on this one. Something else is up in the way she configured her form.
